### ISSUE TITLE
Credentials for Discovery Service Change

### ISSUE THREAD

**Issue by bsullins** [IBM/crypto-discovery-news-sentiment-analysis#13]
It seems the discovery service wants JSON for credentials and not a user/pass. Can you help me resolve this?

from the discovery service credentials page:

_Credentials are provided in JSON format. The JSON snippet lists credentials, such as the API key and secret, as well as connection information for the service._

**Comment by bsullins** [comment]
I was able to get this working w/ the following changes

```!pip install --upgrade "watson-developer-cloud>=2.5.1"```
```
discovery = DiscoveryV1(
    version='2018-08-01',
    url='https://gateway.watsonplatform.net/discovery/api',
    iam_api_key='{apikey}')```

**Comment by stevemar** [comment]
Thanks @bsullins ! I proposed https://github.com/IBM/crypto-discovery-news-sentiment-analysis/pull/14 to use a newer SDK in the notebook.
